### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by aovestdipaperino**

### CODE REVIEW

**Comment by xwatermelonx** [comment]
Thank you very much!

**Comment by Zack148** [comment]
Is this method still working?

**Review by ks1707 — APPROVED** [review]

**Review by Schlauer-Hax — APPROVED** [review]

**Comment by lonkle** [comment]
Maybe the people approving the changes know like @ks1707 or @Schlauer-Hax - but @aovestdipaperino would def be the one to answer this in the end? Especially now that the Windows AltServer repo has been updated for iOS 15 support.

**Comment by lonkelle** [comment]
Hey there @aovestdipaperino - I'm trying to build AltServer for Windows using the build instructions you wrote. But it's failing, do you happen to know if your build instructions are still working and I'm just doing something silly? 😅

**Pull request merged**
